#!/usr/bin/env python3
"""
preview_animations.py — render an on-demand 3s stub of every published
animation template into a video project's `.animation-previews/` folder.

Invocation happens during Phase 3 when the agent sets
`animations_preview_requested: true` in `pipeline_state.json` before
running `complete` at Step 8. The orchestrator then calls this script
as a pre-Step-9 hook.

Mechanism:
  1. Walk `videos/<title>/remotion/src/components/animations/` to find each
     template's `preview/preview.tsx`.
  2. Generate a `.animation-previews/src/PreviewsRoot.tsx` that registers
     one `<Composition id="preview-<template>" component={Preview} />` for
     every template found.
  3. Set up a tiny temporary Remotion entry (pointing at PreviewsRoot.tsx)
     and call `npx remotion render` once per template at low JPEG quality
     (default 60%, 30fps, 90 frames) into
     `.animation-previews/preview-<template>.mp4`.
  4. Report per-template success/failure. Any failure is non-fatal — the
     regular scene render proceeds; previews are diagnostics.

Usage:
    python3 scripts/preview_animations.py <video_dir>
    python3 scripts/preview_animations.py <video_dir> --dry-run

Exit codes:
    0   All previews rendered (or --dry-run with no errors)
    1   One or more previews failed (continuation is allowed — the agent
        will see per-template errors and decide)
    2   Usage error / missing paths
    3   No animations/ published in the video project (no-op with warning)
"""

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def fail(msg: str, code: int = 2) -> "NoReturn":  # noqa: F821
    print(msg, file=sys.stderr)
    sys.exit(code)


def collect_published_previews(anim_dir: Path) -> list:
    """Return list of (template_name, preview_file_path)."""
    out = []
    if not anim_dir.is_dir():
        return out
    for entry in sorted(anim_dir.iterdir()):
        if not entry.is_dir() or entry.name.startswith(".") or entry.name == "_shared":
            continue
        preview = entry / "preview" / "preview.tsx"
        if preview.exists():
            out.append((entry.name, preview))
    return out


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("-") if part)


def write_previews_root(previews: list, dest_root: Path) -> None:
    """Generate the temporary PreviewsRoot.tsx that registers all previews."""
    dest_root.mkdir(parents=True, exist_ok=True)
    lines = [
        "// AUTO-GENERATED by scripts/preview_animations.py — do not edit.",
        "import React from 'react';",
        "import { Composition, registerRoot } from 'remotion';",
        "",
    ]
    for name, preview_path in previews:
        cname = pascal(name) + "Preview"
        rel = preview_path.relative_to(dest_root.parent).as_posix()
        lines.append(f"import {{ Preview as {cname} }} from './{rel}';")
    lines.append("")
    lines.append("const Root: React.FC = () => (")
    lines.append("  <>")
    for name, _ in previews:
        cname = pascal(name) + "Preview"
        comp_id = f"preview-{name}"
        lines.append(
            f"    <Composition id=\"{comp_id}\" component={{{cname}}} "
            f"durationInFrames={{90}} fps={{30}} width={{1920}} height={{1080}} />"
        )
    lines.append("  </>")
    lines.append(");")
    lines.append("registerRoot(Root);")
    lines.append("")
    (dest_root / "PreviewsRoot.tsx").write_text("\n".join(lines), encoding="utf-8")


def render_one(
    entry_rel: str,
    video_dir: Path,
    comp_id: str,
    out_path: Path,
    jpeg_quality: int,
    log_dir: Path,
) -> tuple:
    """Run `npx remotion render` with --entry pointing at PreviewsRoot.tsx.

    Returns (ok, msg). The entry file is the PreviewsRoot.tsx we generated
    into .animation-previews/src/. We pass it via `--entry` so Remotion's
    bundler uses it instead of the project's default Root.tsx (which only
    registers MainVideo+Thumbnail compositions — preview comps wouldn't show).
    """
    cmd = [
        "npx", "remotion", "render", comp_id,
        str(out_path),
        "--entry", entry_rel,
        "--jpeg-quality", str(jpeg_quality),
        "--frames", "0-89",
    ]
    print(f"  $ {' '.join(cmd)}")
    log_path = log_dir / f"{comp_id}.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with open(log_path, "w", encoding="utf-8") as lf:
        try:
            result = subprocess.run(
                cmd,
                cwd=str(video_dir / "remotion"),
                stdout=lf,
                stderr=subprocess.STDOUT,
                text=True,
            )
        except FileNotFoundError as e:
            return False, f"npx not found: {e}"
    if result.returncode == 0:
        return True, f"rendered {out_path.name}"
    return False, f"{comp_id}: exit {result.returncode} (see {log_path})"


def main(argv=None):
    ap = argparse.ArgumentParser(description="Render on-demand previews of every published animation template.")
    ap.add_argument("video_dir", help="Path to the video project directory")
    ap.add_argument("--dry-run", action="store_true",
                   help="Report actions without invoking Remotion")
    ap.add_argument("--jpeg-quality", type=int, default=60,
                   help="JPEG quality for preview frames (default 60)")
    args = ap.parse_args(argv)

    video_dir = Path(args.video_dir).resolve()
    if not video_dir.is_dir():
        fail(f"ERROR: not a directory: {video_dir}")

    rdir = video_dir / "remotion"
    if not rdir.is_dir():
        fail(f"ERROR: {rdir} not found (run scaffold first)", 2)

    anim_dir = rdir / "src" / "components" / "animations"
    previews = collect_published_previews(anim_dir)
    if not previews:
        print(f"WARN: no animation previews found in {anim_dir} — no-op.")
        sys.exit(3)

    print(f"Found {len(previews)} animation preview(s).")

    dest_dir = video_dir / ".animation-previews"
    src_dir = dest_dir / "src"
    if args.dry_run:
        print(f"  (dry-run) would write {src_dir}/PreviewsRoot.tsx")
        for name, _ in previews:
            print(f"  (dry-run) would render preview-{name} -> {dest_dir}/preview-{name}.mp4")
        sys.exit(0)

    # Clean prior previews but keep the dest dir for $STATE log linkage.
    if dest_dir.exists():
        for f in dest_dir.iterdir():
            if f.is_file() and f.suffix == ".mp4":
                f.unlink()
        if src_dir.exists():
            shutil.rmtree(src_dir)
    else:
        dest_dir.mkdir(parents=True)

    # Write PreviewsRoot.tsx into the dest/src tree. We point Remotion at
    # this file by setting it as the Remotion entrypoint via a temporary
    # `--entry` flag. (The Remotion CLI accepts any file that registerRoot
    # has run against.)
    write_previews_root(previews, src_dir)
    entry_rel = (src_dir / "PreviewsRoot.tsx").relative_to(rdir).as_posix()

    log_dir = dest_dir / "logs"

    failures = []
    for name, _ in previews:
        comp_id = f"preview-{name}"
        out_path = dest_dir / f"preview-{name}.mp4"
        ok, msg = render_one(
            entry_rel, video_dir, comp_id, out_path, args.jpeg_quality, log_dir,
        )
        print(f"  {'OK ' if ok else 'FAIL'} {msg}")
        if not ok:
            failures.append(name)

    summary = {
        "total": len(previews),
        "succeeded": len(previews) - len(failures),
        "failed": failures,
    }
    (dest_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    if failures:
        print(f"\nPREVIEW FAILED for {len(failures)} template(s): {failures}")
        sys.exit(1)
    print(f"\nPREVIEW OK — rendered {len(previews)} previews to {dest_dir}")
    sys.exit(0)


if __name__ == "__main__":
    main()
